### ISSUE TITLE
Generate release description using git-cliff-action

### ISSUE THREAD

**Issue by nsyzrantsev** [nsyzrantsev/barkit#14]
# Problem

Release description generates incorrectly.

# Solution

Add this job to cd.yml instead this code https://github.com/nsyzrantsev/barkit/blob/main/.github/workflows/cd.yml#L9-L32

```
jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}
```
